Freescale/gstreamer-imx

src/v4l2src/v4l2_buffer_pool.c
src/v4l2src/v4l2src.c

Copied from a gst1-fsl-plugins-4.0.5, this also makes easy to integrate third-party devices

VIDIOC_QUERYBUF twice to get the physical address

---

src/v4l2src/v4l2src.c

drivers return the actual frame period, which must be greater or equal to the nominal frame period determined by the current video standard

v4l2_captureparm: get the actual frame period if possible

---

src/v4l2src/v4l2_buffer_pool.c
src/v4l2src/v4l2_buffer_pool.h
src/v4l2src/v4l2src.c
src/v4l2src/v4l2src.h

Crop metadata can be processed by imxipuvideotransform if
input-crop property has been set to true.
parameters:
crop-meta-x, crop-meta-y, crop-meta-width, crop-meta-height
example:
gst-launch-1.0 imxv4l2videosrc crop-meta-x=16 crop-meta-y=48
crop-meta-width=688 crop-meta-height=480 fps-n=25 ! 'video/x-raw,
width=720, height=576, format=UYVY, framerate=25/1' !
imxipuvideotransform input-crop=true ! fakesink
720x576
--------------------------------
|              48              |
|   ------------------------   |
|   | 688x480              |   |
|   |                      |   |
|16 |                      | 16|
|   |                      |   |
|   |                      |   |
|   ------------------------   |
|              48              |
--------------------------------
Signed-off-by: …

imxv4l2videosrc: added metadata for crop parameters

---

src/eglvivsink/egl_platform_android.c
src/eglvivsink/gles2_renderer.c
src/eglvivsink/wscript
wscript

The two changesets introduced by this pull request are providing help to build and run the plugins on Android.
* The plugins based on G2D are disabled when building for Android. Indeed the Android framework (through Freescale port) is using the 2D core to perform the composition, therefore it is not available for anything else.
* The link dependency to GLES2 vivante specific functions is removed. The Android NDK, which is used to build the plugins, provides a GLES2 library without any extension which means it is not possible to use any vendor extension directly linking with it. By the way, EGL provides the eglGetProcAddress() helper to request the extensions implementation at runtime allowing to use them without linking with a specific vendor library. The imxeglivsink now uses this method …

eglvivsink: create an android platform.

---

src/eglvivsink/egl_platform_wayland.c

Sometimes, after setting gstreamer pipeline to NULL state, the mainloop will blocked in wl_display_dispatch, so the mainloop can't receive the GSTIMX_EGLWL_CMD_STOP_MAINLOOP from control pipe. Therefore, the gst_imx_egl_viv_sink_gles2_renderer_stop will never return. 
From the wayland doc, the wl_display_dispatch_pending  will dispatch without block, so we can use it instead.

fix the blocked issue in mainloop

---

src/eglvivsink/egl_platform_wayland.c

eglSwapBuffers will call wl_surface_commit. The current additional
commit causes the compositor to flip buffers with the damage.
Then when eglSwapBuffers calls commit the compositor gets a commit
with empty damage.
Signed-off-by: Richard Röjfors <richard@puffinpack.se>

eglvivsink: wayland: Do not commit before buffers are swapped

---

src/v4l2src/v4l2src.c
src/v4l2src/v4l2src.h

v4l2src: Workaround for missing field order in NXP drivers

---

src/vpu/encoder_base.c
src/vpu/encoder_base.h

I have added code which exposes a **me-search-range** property for all imxvpuenc_* encoders. A motion estimation search window can be specified in imxvpuapi imxvpuapi.h but only the default value (0) was used in gstreamer-imx up to now. There are 4 choices:
```
typedef enum
{
IMX_VPU_ENC_ME_SEARCH_RANGE_256x128 = 0,
IMX_VPU_ENC_ME_SEARCH_RANGE_128x64,
IMX_VPU_ENC_ME_SEARCH_RANGE_64x32,
IMX_VPU_ENC_ME_SEARCH_RANGE_32x32
}
ImxVpuEncMESearchRanges;
```
A smaller  search range reduces the memory read bandwidth needed for encoding. This is crucial in bandwidth limited applications. Especially if the video frame size is smaller, the default (256x128 pixel) seems to be overkill.
Test pipeline (VPU read bandwith reduced by about 13%, measured with mmdc):
```
gst-launch-1.0 imxv4l2videosrc …
```

me-search-range property exposed

---

src/v4l2src/v4l2_buffer_pool.c
src/v4l2src/v4l2src.c

Fixing the format to I420 in get_caps doesn't allow the following
pipeline on a YUY2 capture device whereas it should work:
$ gst-launch-1.0 imxv4l2videosrc device=/dev/video1 ! video/x-raw, \
format=YUY2 ! fakesink
Removing the hardcoded pixel_format leaves it to the negotiate function
to later return the proper format capability, making the plugin more
flexible and now returning a proper error message if the format
requested cannot be negotiated:
streaming task paused, reason not-negotiated (-4)
Another solution would be to limit the format to YUY2 and I420 but it
requires to get a GstStructure from the caps after creation and use
gst_structure_set_value() which isn't as easy as removing the format
field.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

v4l2src: remove format restriction in get_caps function

---

src/v4l2src/v4l2_buffer_pool.c

Since MAP_FAILED is 0xFFFFFFFF, the assertion would never occur.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

v4l2src: fix g_assert to check mmap return value

---

src/common/phys_mem_meta.c

There is a TODO in gst_imx_phys_mem_meta_transform about region copy, and as it stands now it is unfortunately not correct (leading to losing the meta_data upon whole buffer copy).
This can be checked by comparing with other examples such as in gstvideometa.c or gstaudiometa.c etc; typically nothing should happen if (region->copy) (as mentioned in the debug log statement) and lots if not a region copy.

phys_mem_meta: properly check for region copy

---

src/v4l2src/v4l2src.c

Since this format was added in kernel 3.18, any prior version will
fail to compile.
Issue reported by Buildroot autobuilder with 3.10 kernel headers:
http://autobuild.buildroot.net/results/b46/b460a770c8f4e992d29dde8fe37fc23a949937f2/
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

v4l2src: Add V4L2_PIX_FMT_XRGB555X check

---

src/vpu/decoder.c

gst_video_decoder_set_output_state() returns a new GstVideoCodecState
however we're not interested in using it. Drop the reference to fix a leak.
Signed-off-by: Doug Nazar <nazard@nazar.ca>

vpu: decoder: Drop ref to unused GstVideoCodecState

---

src/v4l2src/v4l2src.c

Signed-off-by: Tim Harvey <tharvey@gateworks.com>

v4l2src: Fix compile prior to Gstreamer 1.3.1

---

src/blitter/blitter.c
src/blitter/blitter.h
src/blitter/compositor.c
src/compositor/compositor.c
src/compositor/compositor.h

If a single input frame is used for multiple output frames, we would
otherwise copy multiple times which can easily go to the limit of the
memory bandwidth.

compositor: Only copy compositor input buffers to DMA memory once

---

src/vpu/decoder_framebuffer_pool.c

This can happen if the buffer is released before it was actually used,
e.g. when renegotiating at the very beginning. Prevents a crash
otherwise.

vpu: Handle releasing of buffers without assigned framebuffer

---

src/common/phys_mem_allocator.c
src/common/phys_mem_allocator.h
wscript

But only optionally, if not available have a simple copy of the struct
for backwards compatibility.
https://bugzilla.gnome.org/show_bug.cgi?id=779067

Use new GstPhysMemory from gst-plugins-bad

---

src/common/gstimxcommon.pc.in
src/common/wscript

Necessary when implementing external sinks to retrieve the mapped
physical memory address from gstreamer buffers.

Make gstimxcommon library public

---

src/v4l2src/v4l2sink.c
src/v4l2src/v4l2sink.h
src/v4l2src/v4l2src.c

This only handles BGRA (with dropping alpha) and BGRx currently, and
requires physmem buffers as input.

Initial v4l2sink implementation

---

src/audio/uniaudio_decoder.c
src/g2d/pango/basetextoverlay.c

The audio codec wasn't storing it's copy of the codec_data so it was never being freed after it was finished.
The g2dpango module was missing the prototypes for the physical memory allocator.

Fixes a memory leak and a missing prototype.

---

src/vpu/decoder.c

* This fixes and endless loop condition that may happen when
gst_imx_vpu_decoder_finish() is called in no_wait mode.

Endless loop at gst_imx_vpu_decoder_finish() when in no_wait mode (#179)

---

ext/audio/meson.build

The mp3encoder dependency relies on the fslcodec_libdirvar, which used to be set
only if the libfslaudiocodec library is found. This patch fixes the following
error:
| Dependency libfslaudiocodec skipped: feature uniaudiodec disabled
| Message: Installed fslaudiocodec library not found, or user disabled uniaudiodec element compilation - uniaudio decoder will not be built
|
| ext/audio/meson.build:21:0: ERROR:  Unknown variable "fslcodec_libdirvar".
|

ext/audio: Fix build issue when uniaudiodec is disabled

---

src/audio/uniaudio_decoder.c

If we didn't need to reorder the audio channels, we leak the
unnecessary allocation.
Signed-off-by: Doug Nazar <nazard@nazar.ca>

audio: Only allocate reordered_channel_positions if needed

---

ext/vpu/gstimxvpucommon.c

Brute force attempt, at least fixes the build for me. Feel free to use something more elaborate.

fix build if gstreamer is built without debug API

---

src/g2d/pango/basetextoverlay.c

We discovered a missing unref in the imxg2dtextoverlay plugin, this meant that the imxg2dvideotransform output buffer was not being freed when the pipeline was pulled down. Eventually fixed it with this patch. hope it is useful to you. 
Interestingly this leak only seemed to manifest when we constructed our own pipeline. Using a playbin element (patched to use imxg2dtextoverlay) didn't have the leak, intrigued as to whether any maintainers know how this is "cleaning up" without this patch.
Mark.

unref video_frame memory after phys_memory check

---

src/v4l2video/v4l2src.c

This extends the range of supported video format about YUY2 format
that's used for example in OV5640 camera sensor.
Signed-off-by: Bartosz Bilas <bartosz.bilas@hotmail.com>

v4l2video: v4l2: add support of YUYV pixel format

---

src/blitter/video_sink.c
src/blitter/video_sink.h

Added new optional feature, clear the screen when relocating the video window.
Fixes: #186

video_sink: clear on relocate.

---

ext/vpu/gstimxvpuenc.c
ext/vpu/gstimxvpuenc.h
ext/vpu/gstimxvpuench263.c
ext/vpu/gstimxvpuench264.c
ext/vpu/gstimxvpuencjpeg.c
ext/vpu/gstimxvpuencmpeg4.c
ext/vpu/gstimxvpuencvp8.c

This is currently only enabled for H264 and could possibly be enabled
later for H265 too once an encoder for it is added.
Fixes https://github.com/Freescale/gstreamer-imx/issues/284

imxvpuenc: Add support for intra-refresh

---

ext/vpu/gstimxvpudec.c
ext/vpu/gstimxvpuenc.c

And if handle_frame() gets woken up in STOPPING/INACTIVE state then
return GST_FLOW_FLUSHING immediately.
----
CC @dv1

imx: Wake up all waiters on the decoding thread condition variable

---

ext/vpu/gstimxvpudec.c

Signed-off-by: Doug Nazar <nazard@nazar.ca>
----
Trivial port of https://github.com/Freescale/gstreamer-imx/pull/299

Unlock decoder_context on fatal error while decoding.
